#!/usr/bin/python

import argparse

def main():
	parser = argparse.ArgumentParser(description='Search several files for pattern')
	parser.add_argument('newvalues', nargs='+', help='new values')
	parser.add_argument('-i','--input', help='input file')
	parser.add_argument('-n','--name', help='attribute name in input file')
	parser.add_argument('-v','--value', help='attribute value in input file')

	args = parser.parse_args()

	outcore=args.input.partition(args.name)[0] + args.name
	outsuffix=args.input.partition(args.value)[2]
	#print outcore
	#print outsuffix
	
	ifile = open(args.input, 'r')
	lines=ifile.readlines()
	ifile.close()
	
	for v in args.newvalues:
		oldpattern=args.name+"="+args.value
		newpattern=args.name+"="+v
		outname=outcore+v+outsuffix
		#print outname, oldpattern, newpattern
		f=open(outname, 'w')
		for l in lines:
			f.write(l.replace(oldpattern, newpattern))
		f.close()

if __name__=="__main__":
	main()
